services:
  gcc:
    image: nyacpp/raspi_cross_gcc
    build: raspi_cross_gcc
    entrypoint: bash
  main:
    image: nyacpp/raspi_cross_ros2
    build: .
    volumes:
      - ~/raspi:/raspi
      - ~/raspi/usr/lib/gcc:/cross/lib/gcc
      - ~/ros_humble:/home/pi/ros_humble
    entrypoint: bash
    working_dir: /home/pi/ros_humble
